packages:
  - apps/*
  - packages/*

catalog:
  "@solid-primitives/bounds": ^0.1.0
  "@solid-primitives/refs": ^1.1.1
  "@solid-primitives/scheduled": ^1.5.1
  "@tanstack/solid-table": ^8.21.3
  bumpp: ^10.2.3
  commit-and-tag-version: ^12.5.0
  solid-js: ^1.9.7
  solid-tiny-context: ^0.1.2
  solid-tiny-utils: ^0.6.0
  typescript: ^5.9.2
  vitest: ^3.2.4

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild
