packages:
  - apps/*
  - packages/*

catalog:
  "@solid-primitives/bounds": ^0.1.0
  "@solid-primitives/refs": ^1.1.1
  "@solid-primitives/scheduled": ^1.5.1
  bumpp: ^10.2.3
  rolldown-plugin-solid: ^0.2.1
  solid-js: ^1.9.7
  solid-tiny-context: ^0.2.3
  solid-tiny-utils: ^0.7.1
  tsdown: ^0.15.9
  typescript: ^5.9.2
  vitest: ^3.2.4
  unocss: ^66.5.1

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild
