packages:
  - apps/*
  - packages/*

catalog:
  '@solid-primitives/bounds': ^0.1.0
  '@solid-primitives/refs': ^1.1.1
  '@solid-primitives/scheduled': ^1.5.1
  '@tanstack/solid-table': ^8.21.3
  bumpp: ^10.2.3
  rolldown-plugin-solid: ^0.2.1
  solid-js: ^1.9.7
  solid-tiny-context: 0.1.3
  solid-tiny-utils: 0.6.0
  tsdown: ^0.14.2
  typescript: ^5.9.2
  vitest: ^3.2.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
